const ButtonsList = [
    {
        name:"C",
        value:"C",
        className:"operator1",
        text:"C"
    },
    {
        name:" Backspace",
        value:" &#8592;",
        className:"operator1",
        text:" &#8592;"
    },
    {
        name:"%",
        value:"%",
        className:"operator1",
        text:"%"
    },
    {
        name:"(",
        value:"(",
        className:"operator1",
        text:"("
    },
    {
        name:")",
        value:")",
        className:"operator1",
        text:")"
    },
//----------- 2nd row
    {
        name:"sin",
        value:"sin",
        className:"operator1",
        text:"sin"
    },
    {
        name:"square",
        value:"&#178;",
        className:"operator1",
        text:" x<sup>2</sup>"
    },
    {
        name:"&#8730;",
        value:"&#8730;",
        className:"operator1",
        text:"&#8730;"
    },
    {
        name:"raciprocal",
        value:"raciprocal",
        className:"operator1",
        text:"1/x"
    },
    {
        name:"/",
        value:"/",
        className:"operator",
        text:`&divide;`
    },

    //--------3rd row
    {
        name:"cos",
        value:"cos",
        className:"operator1",
        text:"cos"
    },
    {
        name:"7",
        value:"7",
        className:"",
        text:"7"
    },
    {
        name:"8",
        value:"8",
        className:"r",
        text:"8"
    },
    {
        name:"9",
        value:"9",
        className:"",
        text:"9"
    },
    {
        name:"*",
        value:"*",
        className:"operator",
        text:"&times;"
    },
    //---------------4th row
    {
        name:"tan",
        value:"tan",
        className:"operator1",
        text:"tan"
    },
    {
        name:"4",
        value:"4",
        className:"",
        text:"4"
    },
    {
        name:"5",
        value:"5",
        className:"",
        text:"5"
    },
    {
        name:"6",
        value:"6",
        className:"",
        text:"6"
    },
    {
        name:"-",
        value:"-",
        className:"operator",
        text:"-"
    },
    //----------5th row
    {
        name:"log10",
        value:"log10",
        className:"operator1",
        text:"log"
    },
    {
        name:"1",
        value:"1",
        className:"",
        text:"1",
    },
    {
        name:"2",
        value:"2",
        className:"",
        text:"2",
    },
    {
        name:"3",
        value:"3",
        className:"",
        text:"3",
    },
    {
        name:"+",
        value:"+",
        className:"operator",
        text:"+"
    },
    //--------6th row
    {
        name:"log",
        value:"log",
        className:"operator1",
        text:"ln"
    },
    {
        name:"plusminus",
        value:"plusminus",
        className:"",
        text:"+/-"
    },
    {
        name:"0",
        value:"0",
        className:"",
        text:"0"
    },
    {
        name:".",
        value:".",
        className:"",
        text:"."
    },
    {
        name:"=",
        value:"=",
        className:"operator",
        text:"="
    },
   
];

export default ButtonsList;
