const ButtonsList = [
    {
        name:"C",
        value:"C",
        className:"operator1",
        onclick:()=>null,
        onkeypress:()=>null,
        text:"C"
    },
    {
        name:" &#8592;",
        value:" &#8592;",
        className:"operator1",
        onclick:()=>null,
        onkeypress:()=>null,
        text:" &#8592;"
    },
    {
        name:"",
        value:"%",
        className:"operator1",
        onclick:()=>null,
        onkeypress:()=>null,
        text:"%"
    },
    {
        name:"",
        value:"(",
        className:"operator1",
        onclick:()=>null,
        onkeypress:()=>null,
        text:"("
    },
    {
        name:"",
        value:")",
        className:"operator1",
        onclick:()=>null,
        onkeypress:()=>null,
        text:")"
    },

    {
        name:"squarey",
        value:"squarey",
        className:"operator1",
        onclick:"",
        onkeypress:"",
        text:" x<sup>y</sup>"
    },
    {
        name:"square",
        value:"&#178;",
        className:"operator1",
        onclick:"",
        onkeypress:"",
        text:" x<sup>2</sup>"
    },
    {
        name:"&#8730;",
        value:"&#8730;",
        className:"operator1",
        onclick:"",
        onkeypress:"",
        text:"&#8730;"
    },
    {
        name:"raciprocal",
        value:"raciprocal",
        className:"operator1",
        onclick:"",
        onkeypress:"",
        text:"1/x"
    },
    {
        name:"&divide;",
        value:"/",
        className:"operator",
        onclick:"",
        onkeypress:"",
        text:`&divide;`
    },
    {
        name:"sin",
        value:"sin",
        className:"operator1",
        onclick:"",
        onkeypress:"",
        text:"  sin"
    },
    {
        name:"7",
        value:"7",
        className:"",
        onclick:"",
        onkeypress:"",
        text:"7"
    },
    {
        name:"8",
        value:"8",
        className:"r",
        onclick:"",
        onkeypress:"",
        text:"8"
    },
    {
        name:"9",
        value:"9",
        className:"",
        onclick:"",
        onkeypress:"",
        text:"9"
    },
    {
        name:"&times;",
        value:"*",
        className:"operator",
        onclick:"",
        onkeypress:"",
        text:"&times;"
    },
    {
        name:"cos",
        value:"cos",
        className:"operator1",
        onclick:"",
        onkeypress:"",
        text:"cos"
    },
    {
        name:"4",
        value:"4",
        className:"",
        onclick:"",
        onkeypress:"",
        text:"4"
    },
    {
        name:"5",
        value:"5",
        className:"",
        onclick:"",
        onkeypress:"",
        text:"5"
    },
    {
        name:"6",
        value:"6",
        className:"",
        onclick:"",
        onkeypress:"",
        text:"6"
    },
    {
        name:"-",
        value:"-",
        className:"operator",
        onclick:"",
        onkeypress:"",
        text:"-"
    },
    {
        name:"tan",
        value:"tan",
        className:"operator1",
        onclick:"",
        onkeypress:"",
        text:"tan"
    },
    {
        name:"1",
        value:"2",
        className:"",
        onclick:"",
        onkeypress:"",
        text:"1"
    },
    {
        name:"2",
        value:"2",
        className:"",
        onclick:"",
        onkeypress:"",
        text:"2"
    },
    {
        name:"3",
        value:"3",
        className:"",
        onclick:"",
        onkeypress:"",
        text:"3"
    },
    {
        name:"+",
        value:"+",
        className:"operator",
        onclick:"",
        onkeypress:"",
        text:"+"
    },
    {
        name:"log10",
        value:"log10",
        className:"operator1",
        onclick:"",
        onkeypress:"",
        text:"log"
    },
    {
        name:"plusminus",
        value:"plusminus",
        className:"",
        onclick:"",
        onkeypress:"",
        text:"+/-"
    },
    {
        name:"0",
        value:"0",
        className:"",
        onclick:"",
        onkeypress:"",
        text:"0"
    },
    {
        name:".",
        value:".",
        className:"",
        onclick:"",
        onkeypress:"",
        text:"."
    },
    {
        name:"=",
        value:"=",
        className:"operator",
        onclick:"",
        onkeypress:"",
        text:"="
    },
   
];

export default ButtonsList;
